---
- name: "Helloworld installation"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create default containers
      docker_container:
        name: "helloworld"
        image: "severine972/helloworld:latest"
        ports: 80:80
...
